services:
  yourls:
    image: yourls
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - ${PORT:-80}
    environment:
      YOURLS_SITE: ${PROTO}://${DOMAIN:?Missing site DOMAIN}
      YOURLS_USER: ${YOURLS_USER:?Missing admin username}
      YOURLS_PASS: ${YOURLS_PASS:?Missing admin password}
      YOURLS_DB_HOST: ${YOURLS_DB_HOST}
      YOURLS_DB_USER: ${YOURLS_DB_USER:?No database user set}
      YOURLS_DB_PASS: ${YOURLS_DB_PASS:?No database password set}
      YOURLS_DB_NAME: ${YOURLS_DB_NAME:-yourls}
      YOURLS_DB_PREFIX: ${YOURLS_DB_PREFIX}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo.entrypoints=websecure"
      - "traefik.http.routers.matomo.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.matomo.tls.certresolver=http-challenge"
    networks:
      - default
      - traefik-proxy

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Missing Mysql root password}
      MYSQL_DATABASE: ${YOURLS_DB_NAME:-yourls}
      MYSQL_USER: ${YOURLS_DB_USER}
      MYSQL_PASSWORD: ${YOURLS_DB_PASS}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=\"${MYSQL_ROOT_PASSWORD}\" --execute \"SHOW DATABASEs;\""
      interval: 5s
      timeout: 300s
      retries: 60

networks:
  default:
  traefik-proxy:
    external: true
